"""
Django settings for drmvid project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
from datetime import timedelta

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '#7l+y##lfsrqdal7r(4ya&z6gjlv0o#pxin(fbv=y7m1ot$727'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 3rd party apps
    'rest_framework',
    'video_encoding',
    'django_rq',
    # drmvid apps
    'vid',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drmvid.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drmvid.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',
        # make sure that timeout is long enough to
        # convert even very large videos
        'DEFAULT_TIMEOUT': 3600,  # 1 Hour in seconds
    },
    # 'with-sentinel': {
    #     'SENTINELS': [('localhost', 26736), ('localhost', 26737)],
    #     'MASTER_NAME': 'redismaster',
    #     'DB': 0,
    #     'PASSWORD': '',
    #     'SOCKET_TIMEOUT': None,
    #     'CONNECTION_KWARGS': {
    #         'socket_connect_timeout': 0.3
    #     },
    # },
    # 'high': {
    #     # 'URL': os.getenv('REDISTOGO_URL', 'redis://localhost:6379/0'), # If you're on Heroku
    #     # 'HOST': 'localhost',
    #     # 'PORT': 6379,
    #     # 'DB': 0,
    #     'DEFAULT_TIMEOUT': 500,
    # },
    # 'low': {
    #     # 'HOST': 'localhost',
    #     # 'PORT': 6379,
    #     # 'DB': 0,
    #     'DEFAULT_TIMEOUT': 100,
    # }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'


# DRMVid Settings

# Use this to upload any files
UPLOAD_PATH = os.path.join(BASE_DIR, 'uploads')
VID_UPLOAD_PATH = os.path.join(UPLOAD_PATH, 'videos')
VID_ALLOWED_MIMETYPES = [
    'video/mp4',
    'video/x-matroska',
    'video/mpeg',
    'video/avi',
    'video/msvideo',
    'video/x-msvideo',
]
VID_ALLOWED_EXTENSIONS = [
    'mp4',
    'mkv',
    'mpeg',
    'avi',
]
VIDEO_ENCODING_FORMATS = {
    'FFmpeg': [
        {
            'name': 'webm_sd',
            'extension': 'webm',
            'params': [
                '-b:v', '1000k', '-maxrate', '1000k', '-bufsize', '2000k',
                '-codec:v', 'libvpx', '-r', '24',
                '-vf', 'scale=-1:480', '-qmin', '10', '-qmax', '42',
                '-codec:a', 'libvorbis', '-b:a', '128k', '-f', 'webm',
           ],
        },
        {
            'name': 'mp4_sd',
            'extension': 'mp4',
            'params': [
                '-codec:v', 'libx264', '-crf', '20', '-preset', 'medium',
                '-b:v', '1000k', '-maxrate', '1000k', '-bufsize', '2000k',
                '-vf', 'scale=-2:480',
                '-codec:a', 'aac', '-b:a', '128k', '-strict', '-2',
            ],
        },
        # {
        #     'name': 'webm_hd',
        #     'extension': 'webm',
        #     'params': [
        #         '-codec:v', 'libvpx',
        #         '-b:v', '3000k', '-maxrate', '3000k', '-bufsize', '6000k',
        #         '-vf', 'scale=-1:720', '-qmin', '11', '-qmax', '51',
        #         '-acodec', 'libvorbis', '-b:a', '128k', '-f', 'webm',
        #     ],
        # },
        # {
        #     'name': 'mp4_hd',
        #     'extension': 'mp4',
        #     'params': [
        #         '-codec:v', 'libx264', '-crf', '20', '-preset', 'medium',
        #         '-b:v', '3000k', '-maxrate', '3000k', '-bufsize', '6000k',
        #         '-vf', 'scale=-2:720',
        #         '-codec:a', 'aac', '-b:a', '128k', '-strict', '-2',
        #     ],
        # },
     ]
}


# SimpleJWT settings

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
}