# Generated by Django 2.2.3 on 2019-08-16 14:50

import django.core.files.storage
from django.db import migrations, models
import vid.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRMVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('video', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/home/saurav/projects/uploads/', location='/home/saurav/projects/uploads/'), upload_to=vid.models.file_upload_path)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'drm_video',
            },
        ),
    ]
