# Generated by Django 2.2.4 on 2019-08-17 16:05

import django.core.files.storage
from django.db import migrations, models
import vid.models
import video_encoding.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRMVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('created_dtm', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('duration', models.FloatField(editable=False, null=True)),
                ('video', video_encoding.fields.VideoField(height_field='height', max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/home/saurav/projects/drmvid/uploads/videos', location='/home/saurav/projects/drmvid/uploads/videos'), upload_to=vid.models.file_upload_path, validators=[vid.models.extension_validator, vid.models.mime_validator], width_field='width')),
            ],
            options={
                'db_table': 'drm_video',
            },
        ),
    ]
