# Generated by Django 2.2.3 on 2019-08-16 17:19

import django.core.files.storage
from django.db import migrations, models
import vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmvideo',
            name='video',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/home/saurav/projects/drmvid/uploads/videos', location='/home/saurav/projects/drmvid/uploads/videos'), upload_to=vid.models.file_upload_path),
        ),
    ]
