# Generated by Django 2.2.3 on 2019-08-16 21:46

import django.core.files.storage
from django.db import migrations, models
import vid.models


class Migration(migrations.Migration):

    dependencies = [
        ('vid', '0002_auto_20190816_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drmvideo',
            name='video',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(base_url='/home/saurav/projects/drmvid/uploads/videos', location='/home/saurav/projects/drmvid/uploads/videos'), upload_to=vid.models.file_upload_path, validators=[vid.models.extension_validator, vid.models.mime_validator]),
        ),
    ]
